test_dir: "test_data"
out_csv: "submission.csv"
recursive: true

num_frames: 16
agg: "mean"          # "mean" or "median"

# 전처리
image_size: 224
clip_mean: [0.48145466, 0.4578275, 0.40821073]
clip_std:  [0.26862954, 0.26130258, 0.27577711]

# 추론 배치 (영상 프레임 배치)
frame_batch_size: 16

# 모델
model_pt: "model/model.pt"

# 출력 CSV
csv_header: ["filename", "label"]
